"use client"
import { useState } from 'react'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { PlusIcon } from 'lucide-react'

export function FAQSection() {
  const [openItem, setOpenItem] = useState<string>('')

  const faqItems = [
    {
      id: '1', question: 'How does ViralReel work?',
      answer: 'ViralReel is a tool that helps you create viral-tested social content in real-time. It uses AI to analyze your content and prepare it for video transformation.'
    },
    {
      id: '2', question: 'Does ViralReel require any video editing skills?',
      answer: 'No, ViralReel does not require any video editing skills. It is a simple tool that allows you to create viral-tested social content in real-time.'
    },
    {
      id: '3', question: 'What types of videos can I create?',
      answer: 'You can create a wide range of videos, including split-screen videos, fake text videos, Reddit conversation videos, and more.'
    },
    {
      id: '4', question: 'Who can benefit most from ViralReel?',
      answer: 'Anyone who wants to create viral-tested social content in real-time can benefit from ViralReel.'
    },
    {
      id: '5', question: 'Is the content generated by ViralReel copyright-free?',
      answer: 'Yes, the content generated by ViralReel is copyright-free. You can use it for your own projects without any worries.'
    },
    {
      id: '6', question: 'Can I add captions?',
      answer: 'Yes, you can add captions to your videos. ViralReel allows you to add captions to your videos.'
    },
    {
      id: '7', question: 'Is ViralReel free to use?',
      answer: 'Yes, ViralReel is free to use. You can use it for your own projects without any worries.'
    },
    {
      id: '8', question: 'I have more questions!',
      answer: 'You can contact us at support@viralreel.ai and we will be happy to help you.'
    },
  ]

  return (
    <div className="w-full max-w-[680.80px] mx-auto px-4 md:px-6 py-8 md:py-12 mt-48">
      <h2 className="text-center text-slate-950 text-4xl md:text-5xl lg:text-6xl font-medium font-['Inter'] leading-tight md:leading-[67.20px] mb-5 md:mb-[26px]">
        Your questions,
        <br />
        <span className='text-orange-400'>answered</span>

      </h2>
      <Accordion
        type="single"
        collapsible
        value={openItem}
        onValueChange={setOpenItem}
        className="space-y-4 md:space-y-[25.60px]"
      >
        {faqItems.map((item) => (
          <AccordionItem
            key={item.id}
            value={item.id}
            className="border-none"
          >
            <AccordionTrigger
              className="w-full min-h-[60px] md:h-[77.60px] p-4 md:p-[24.80px] bg-white rounded-xl md:rounded-2xl border border-[#4d7fed]/20 flex justify-between items-center"
            >
              <span className="text-slate-950 text-base md:text-lg font-semibold font-['Inter'] leading-normal md:leading-7 text-left">
                {item.question}
              </span>
              <div className={`p-1.5 md:p-2 rounded-full shrink-0 ml-2 transition-colors duration-200 ${openItem === item.id ? 'bg-[#4d7fed]' : 'bg-[#4d7fed]/10'
                }`}>
                <PlusIcon className={`w-3 h-3 md:w-4 md:h-4 transition-transform duration-200 ${openItem === item.id ? 'transform rotate-45 text-white' : 'text-[#4d7fed]'
                  }`} />
              </div>
            </AccordionTrigger>
            <AccordionContent className="pt-3 md:pt-4 px-4 md:px-[24.80px]">
              <p className="text-slate-700 text-sm md:text-base">
                {item.answer}
              </p>
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  )
}

